### ISSUE TITLE
No media folder found

### ISSUE THREAD

**Issue by devkaiwang** [GameTechDev/DeferredCoarsePixelShading#1]
The media folder is missing so there is no mesh or texture to run with.

**Comment by rpsathe** [comment]
Hi Kai, Unfortunately I have left Intel over 6 months ago, so have no access to the content. But you can try getting the contents from Andrew's work and try it with that. That should work. Refer to his own licencing
requirements for the content. 
https://software.intel.com/en-us/articles/deferred-rendering-for-current-and-future-rendering-pipelines
Let me know if it works.

**Comment by StephanieB5** [comment]
If you copy the media folder up to the parent folder it will work.   Hope this helps!

**Comment by DaveBookout-Intel** [comment]
the media directory needs to be in the working directory when you run the executable. When running from visual studio, the working directory is the project directory, and the media directory is in the project directory. to run outside of visual studio, either call the executable from the project directory, or, as Stephanie said, move the files so that the media directory is in your working directory.
